meta_product_name: "Treen"
meta_title: "Treen - trust for concious fashion where ever you are"
meta_description: "This mobile app provides validated expertise on sustainable fashion brands on a map based navigation with filter options based on your personal ethical standards"
meta_image: "meta_cover.png" # should exist in `app/assets/images/`
